### ISSUE TITLE
Dodělání entit a základních controllerů

### ISSUE THREAD

**Issue by FiXerCz** [radike/issue-tracker#2]
# Seznam věcí, které je potřeba dodělat
- V případě, že naleznete další úkon, přidejte jej do tabulky.
- Čeho se chcete ujmout, označte svým GitHub nickem.
- Pokud je nějaký úkon nesmysl, tak jej ~~škrtněte~~ (nemažte je)
## Seznam

| Hotovo | Úkon | Kdo se toho ujme |
| --- | --- | --- |
| ne | Dodělat anotace k entitám, aby docházelo k automatickým kontrolám validnosti (anotace required, pro určení délky stringu, popisky HTML elementu, hláška v případě nevyplnění aj.) | @FiXerCz |
| ne | Dodělat šablonu pro výběr uživatelů u projektu (vztah many to many) | @FiXerCz |
| ne | Dodělat entitu StatusWorkflow | @tomillie |
| ne | Dodělat enumy pro entitu Issue a začlenit je do ní |  |
| ne | ~~Zrušení entity State a její nahrazení pouze enumem. _Toto je jen návrh, tak kdyžtak napište pro a proti :)_~~ |  |

Pokud se vám cokoliv nebude zdát, tak to sem pište. Už je hodně hodin a moc mi to nemyslí, takže jsem možná něco přehlíd nebo špatně pochopil..

**Comment by petrinecp** [comment]
To nahradenie entity State za Enum mi stále nejde nějak do hlavy, ak to ma byt editovatelné ako sa píše v zadaní tak predsa to nemôže byť Enum, kebyže v databázi upravíš tabulku, ktorá reprezentuje enum napr. tak ze to je jednostlpcova tabulka s číselnými hodnotami a ty tam přidáš nový záznam s nasledujúcim číslom tak v kóde sa ti ten výčtový typ nijak neupravý a teda by sa ti ta hodnota nemala na čo namapovať keby si chcel potom získať entitu,  ktorá by mala nastavenú tú novú hodnotu pre ten atribút stavu...

**Comment by FiXerCz** [comment]
@petrinecp Jasne, mas pravdu. Nevsiml jsem si toho bodu, ze to ma byt mozne pridavat. Puvodne jsem to zamyslel tak, ze budeme mit par zakladnich stavu a ty pouzivat, ale to by odporovalo zadani.

**Comment by tomillie** [comment]
Mimochodom s tým rozdelením práce to robíme presne naopak, ako by sa to malo robiť :D .. na každú novú funkcionalitu/bug/požiadavok by sa mal vytvoriť Issue a to si potom môže na seba niekto priradiť a začať na tom pracovať.. a keď sa commituje, tak do commit message sa dá odkazovať presne na konkrétne issue (napr. #2) a človek vie hneď, čo ten commit obsahuje... to sme ináč mohli namiesto tohto github issue trackera rovno použiť nejaký zdieľaný excel..

**Comment by FiXerCz** [comment]
To sice ano, ale ono si docela dlouho nic nedelo a chtel jsem jen sepsat, co nam chybi, at se nekam pohneme...
Jestli se ti chce, tak to klidne rozdel na jednotlive issues, at je to prehlednejsi.

**Comment by tomillie** [comment]
V pohode, ja len či sa o tom vie ;) .. dostanem sa k tomu asi až zajtra, tak to potom môžem spísať
