### ISSUE TITLE
Change Issues Index page into Paged Index page

### ISSUE THREAD

**Issue by radike** [radike/issue-tracker#24]
see https://msdn.microsoft.com/en-us/magazine/gg650669.aspx, #22, and #23

**Comment by petrinecp** [comment]
maybe more relevant for MVC 5
http://www.asp.net/mvc/overview/getting-started/getting-started-with-ef-using-mvc/sorting-filtering-and-paging-with-the-entity-framework-in-an-asp-net-mvc-application

**Comment by radike** [comment]
@petrinecp Nice tutorial :)
