### ISSUE TITLE
Create Repository assembly

### ISSUE THREAD

**Issue by radike** [radike/issue-tracker#31]
Controllers should use repositories instead of directly using DbContext.

**Comment by damolh** [comment]
prototype is accessible on slack or http://ulozto.cz/xWawRwtn/issuetracker-source-zip

**Comment by radike** [comment]
- use AutoMapper instead of implementing own mapper "SimpleMapper"
- please, make sure that the purpose of every new project is clear and the name reveals its content

**Comment by radike** [comment]
Update!
ccc6623e316f7d104f83a48a0ad7ed51a24cc029
@damolh please, reference the issue in commit message like this '#31'

**Comment by radike** [comment]
Notes from our brainstorming:
- remove empty IDataRepository interface or make it useful
- rename generic types to something descriptive e.g. from T to TEntity
- add DTO assembly

**Comment by radike** [comment]
Notes from our brainstorming:
- assemblies should be in real folders = assemblies organization
- repositories should use db context per request
- move DataRepositoryBase to IssueTracker.Entities
- add repositories metods to interfaces in IssueTracker.Data.Contracts
- IIdentifiableEntity should be in IssueTracker.Entities
- DTOs are required, it is not a good design practice to replace DTOs with entities without data annotations and configurations replacing data annotations .. but this should not block our progress => minor issue

**Comment by radike** [comment]
Closing this issue because the repositories are implemented and other minor issues will be solved in the future (probably as part of the task #61).
