### ISSUE TITLE
States should allow reordering

### ISSUE THREAD

**Issue by radike** [radike/issue-tracker#33]

**Comment by tomillie** [comment]
How should be this implemented?
I can think of two possible solutions:
1.) the order of the states is saved in cookies (local)
2.) the order of the states is saved in database
- it is necessary to create a new property
- the order is global (all users have same order)

**Comment by radike** [comment]
I think that the order of the states could be stored in the database as global property if only admins will be able to edit states (and state workflows). Therefore, admins will be responsible for creating the best order of the states ;)
