### ISSUE TITLE
Users are removed after project update

### ISSUE THREAD

**Issue by tomillie** [radike/issue-tracker#35]

**Comment by tomillie** [comment]
Caused by 1 to n  relationship (Project : User).

**Comment by tomillie** [comment]
@FiXerCz could you please take a look at this? in your commit https://github.com/radike/issue-tracker/commit/e9851c487a230b104c66bf747287dbda7bf8a1b8 you have removed table dbo.ProjectApplicationUser (see the migration file). Users are now saved into dbo.AspNetUser.Project_id, which cause that there is only one to many realationship.

**Comment by FiXerCz** [comment]
Sure. I will look into it. I haven't even noticed that I had removed something. Sorry for confusion..
