### ISSUE TITLE
Display error page instead of redirecting to login page when user tries to access restricted parts o application

### ISSUE THREAD

**Issue by petrinecp** [radike/issue-tracker#52]

**Comment by SamuelBaniar** [comment]
Don't know if it's good solution, but I've seen a few websites loging out user and displaying login page with "access denied" error when user tries to access restricted part

**Comment by petrinecp** [comment]
I don't think it's a good solution, at least not in our application when our login page looks different then the application and the user might think that he has been logged out, and he needs to sign in again to return but in fact he only gets redirected to this page but he is still signed in. If the login form would be displayed in the error page and it would feel that the user is still in the app then maybe but I don't think it's necessary.
